# Generated by Django 2.2.5 on 2019-09-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10)),
                ('financialReturnScore', models.DecimalField(decimal_places=3, max_digits=5)),
                ('growthScore', models.DecimalField(decimal_places=3, max_digits=5)),
                ('multipleScore', models.DecimalField(decimal_places=3, max_digits=5)),
                ('integratedScore', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
